// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7EtuU0Jg3EeDYT2iSm74gbWIX3cUCzfw',
    appId: '1:1028098506758:web:7bd483e2ee533f8e9c0387',
    messagingSenderId: '1028098506758',
    projectId: 'chore-app-94635',
    authDomain: 'chore-app-94635.firebaseapp.com',
    storageBucket: 'chore-app-94635.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMnUvOYkIiVNoWsb9weY5fa-KYI68HkI',
    appId: '1:1028098506758:android:a480cafa46f366189c0387',
    messagingSenderId: '1028098506758',
    projectId: 'chore-app-94635',
    storageBucket: 'chore-app-94635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6T5I0BeGcAXLKPuh8OEy5Z_ECXCi4tq0',
    appId: '1:1028098506758:ios:a58e7dd19dc24abc9c0387',
    messagingSenderId: '1028098506758',
    projectId: 'chore-app-94635',
    storageBucket: 'chore-app-94635.firebasestorage.app',
    iosBundleId: 'com.example.choreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6T5I0BeGcAXLKPuh8OEy5Z_ECXCi4tq0',
    appId: '1:1028098506758:ios:a58e7dd19dc24abc9c0387',
    messagingSenderId: '1028098506758',
    projectId: 'chore-app-94635',
    storageBucket: 'chore-app-94635.firebasestorage.app',
    iosBundleId: 'com.example.choreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7EtuU0Jg3EeDYT2iSm74gbWIX3cUCzfw',
    appId: '1:1028098506758:web:637ec92cdb408d0f9c0387',
    messagingSenderId: '1028098506758',
    projectId: 'chore-app-94635',
    authDomain: 'chore-app-94635.firebaseapp.com',
    storageBucket: 'chore-app-94635.firebasestorage.app',
  );

}